apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: net-loss-template2
spec:
  podGC: 
    strategy: OnWorkflowCompletion
  ttlStrategy:
    secondsAfterCompletion: 0 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 0     # Time to live after workflow is successful
    secondsAfterFailure: 600     # Time to live after workflow failed
  entrypoint: chaos-execution
  archiveLogs: true
  templates:
    - name: chaos-execution
      steps:
        - - name: install-chaos-mesh
            template: install-chaos
        - - name: apply-chaos-experiment
            template: chaos-experiment
        - - name: wait
            template: wait-step
        - - name: remove-chaos-mesh
            template: uninstall-chaos
    
    - name: install-chaos
      container:
        image: alpine/helm
        command: [sh, "-c"]
        args: ["echo 'Installing chaos mesh...'"]

    - name: chaos-experiment
      container:
        image: alpine/helm
        command: [sh, "-c"]
        args: ["echo 'Applying chaos experiment...'"]

    - name: wait-step
      container:
        image: alpine
        command: ["sh", "-c"]
        args: ["echo 'Finished' > /tmp/chaos-mesh-events.txt"]
      outputs:
        artifacts:
        - name: chaos-mesh-events
          path: /tmp/chaos-mesh-events.txt

    - name: uninstall-chaos
      container:
        image: alpine/helm
        command: [sh, "-c"]
        args: ["echo 'Uninstalling chaos mesh...'"]