apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kubebenchtest-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a KubeBench Scan Test
spec: 
  archiveLogs: true
  entrypoint: kube-bench-test
  volumes:
    - name: var-lib-cni
      hostPath:
        path: /var/lib/cni
    - name: var-lib-etcd
      hostPath:
        path: /var/lib/etcd
    - name: var-lib-kubelet
      hostPath:
        path: /var/lib/kubelet
    - name: var-lib-kube-scheduler
      hostPath:
        path: /var/lib/kube-scheduler
    - name: var-lib-kube-controller-manager
      hostPath:
        path: /var/lib/kube-controller-manager
    - name: etc-systemd
      hostPath:
        path: /etc/systemd
    - name: lib-systemd
      hostPath:
        path: /lib/systemd
    - name: srv-kubernetes
      hostPath:
        path: /srv/kubernetes
    - name: etc-kubernetes
      hostPath:
        path: /etc/kubernetes
    - name: usr-bin
      hostPath:
        path: /usr/bin
    - name: etc-cni-netd
      hostPath:
        path: /etc/cni/net.d/
    - name: opt-cni-bin
      hostPath:
        path: /opt/cni/bin/
    - name: proc-mount
      hostPath:
        path: /proc
        type: Directory
    - name: kubelet-mount
      hostPath:
        path: /var/lib/kubelet
        type: Directory
  templates:
  - name: kube-bench-test
    steps:
    - - name: scan-run
        template: kube-bench


  - name: kube-bench 
    nodeSelector:
        kubernetes.io/hostname: argo
    container:
      image: docker.io/aquasec/kube-bench:v0.10.2
      securityContext:
        privileged: true
      volumeMounts:
      - name: var-lib-cni
        readOnly: true
        mountPath: /var/lib/cni
      - name: var-lib-etcd
        readOnly: true
        mountPath: /var/lib/etcd
      - name: var-lib-kubelet
        readOnly: true
        mountPath: /var/lib/kubelet
      - name: var-lib-kube-scheduler
        readOnly: true
        mountPath: /var/lib/kube-scheduler
      - name: var-lib-kube-controller-manager
        readOnly: true
        mountPath: /var/lib/kube-controller-manager
      - name: etc-systemd
        readOnly: true
        mountPath: /etc/systemd
      - name: lib-systemd
        readOnly: true
        mountPath: /lib/systemd/
      - name: srv-kubernetes
        readOnly: true
        mountPath: /srv/kubernetes/
      - name: etc-kubernetes
        readOnly: true
        mountPath: /etc/kubernetes
      - name: usr-bin
        readOnly: true
        mountPath: /usr/local/mount-from-host/bin
      - name: etc-cni-netd
        readOnly: true
        mountPath: /etc/cni/net.d/
      - name: opt-cni-bin
        readOnly: true
        mountPath: /opt/cni/bin/
      - name: proc-mount
        mountPath: /host/proc
        readOnly: true
      command: ["/bin/sh", "-c"]
      args: [ "kube-bench > /tmp/report.txt"]
    outputs:
      artifacts:
      - name: KubeBench-test-report
        path: /tmp/report.txt

